// SkillsOverviewData.jsx
import { FaCss3Alt } from "react-icons/fa";
import {
  PiMicrosoftExcelLogo,
  PiMicrosoftPowerpointLogo,
  PiMicrosoftWordLogo,
} from "react-icons/pi";
import {
  SiC,
  SiCplusplus,
  SiPython,
  SiPhp,
  SiJavascript,
  SiHtml5,
  SiTailwindcss,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiMongodb,
  SiLaravel,
  SiFirebase,
  SiGit,
  SiGithub,
  SiCanva,
  SiNotion,
  SiCodeforces,
  SiCodechef,
  SiLeetcode,
  SiHackerrank,
} from "react-icons/si";

export const SKILLS_OVERVIEW = [
  {
    icon: <SiC />,
    label: "C",
    color: "text-blue-400",
    desc: "Foundation of systems programming. Builds deep understanding of memory management, pointers, and how computers actually work at a low level.",
  },
  {
    icon: <SiCplusplus />,
    label: "C++",
    color: "text-blue-500",
    desc: "Extends C with OOP and the STL. The language of competitive programming, high-performance systems, and game engines.",
  },
  {
    icon: <SiPython />,
    label: "Python",
    color: "text-yellow-400",
    desc: "The go-to for rapid development, automation, data analysis, and the primary language of Machine Learning & AI.",
  },
  {
    icon: <SiPhp />,
    label: "PHP",
    color: "text-indigo-400",
    desc: "Powers server-side web logic at massive scale. The backbone of Laravel and WordPress-driven backend systems.",
  },
  {
    icon: <SiJavascript />,
    label: "JavaScript",
    color: "text-yellow-300",
    desc: "The only language that runs natively in the browser. Essential for building interactive UIs, APIs, and full-stack apps.",
  },
  {
    icon: <SiHtml5 />,
    label: "HTML5",
    color: "text-orange-400",
    desc: "The structural skeleton of every webpage. Semantic HTML improves accessibility, SEO, and maintainability.",
  },
  {
    icon: <FaCss3Alt />,
    label: "CSS3",
    color: "text-sky-400",
    desc: "Brings web layouts to life with styling, animations, and responsive design. The visual layer of the web.",
  },
  {
    icon: <SiTailwindcss />,
    label: "Tailwind CSS",
    color: "text-cyan-400",
    desc: "Utility-first CSS framework for rapidly building custom designs directly in markup — no context switching.",
  },
  {
    icon: <SiReact />,
    label: "React",
    color: "text-cyan-300",
    desc: "Industry-standard UI library for building dynamic, component-driven interfaces with an efficient virtual DOM.",
  },
  {
    icon: <SiNextdotjs />,
    label: "Next.js",
    color: "text-white",
    desc: "Full-stack React framework with SSR, SSG, and edge routing. The modern standard for production-grade web apps.",
  },
  {
    icon: <SiNodedotjs />,
    label: "Node.js",
    color: "text-green-400",
    desc: "Brings JavaScript to the server. Enables fast, scalable REST APIs and real-time applications with a single language stack.",
  },
  {
    icon: <SiMongodb />,
    label: "MongoDB",
    color: "text-green-500",
    desc: "NoSQL document database storing JSON-like data flexibly. Ideal for rapid prototyping and high-scale applications.",
  },
  {
    icon: <SiLaravel />,
    label: "Laravel",
    color: "text-red-400",
    desc: "Elegant PHP framework with built-in auth, ORM, and routing — great for REST API and backend web development.",
  },
  {
    icon: <SiFirebase />,
    label: "Firebase",
    color: "text-amber-400",
    desc: "Google's BaaS platform with real-time database, authentication, hosting, and serverless functions out of the box.",
  },
  {
    icon: <SiGit />,
    label: "Git",
    color: "text-orange-500",
    desc: "Distributed version control that tracks changes and enables team collaboration. A must-have for every developer.",
  },
  {
    icon: <SiGithub />,
    label: "GitHub",
    color: "text-white",
    desc: "The world's largest code hosting platform — central to open source, code review, CI/CD, and team workflows.",
  },
  {
    icon: <SiCanva />,
    label: "Canva",
    color: "text-cyan-500",
    desc: "Intuitive design tool for graphics, presentations, and UI mockups without deep design expertise.",
  },
  {
    icon: <SiNotion />,
    label: "Notion",
    color: "text-white",
    desc: "All-in-one workspace for notes, project planning, knowledge bases, and team documentation.",
  },
  {
    icon: <PiMicrosoftExcelLogo />,
    label: "Excel",
    color: "text-green-400",
    desc: "Powerful spreadsheet tool for data analysis, financial modelling, pivot tables, and workflow automation.",
  },
  {
    icon: <PiMicrosoftWordLogo />,
    label: "Word",
    color: "text-blue-400",
    desc: "Industry-standard word processor for reports, documentation, and professional correspondence.",
  },
  {
    icon: <PiMicrosoftPowerpointLogo />,
    label: "PowerPoint",
    color: "text-orange-500",
    desc: "Go-to tool for professional presentations with animations, charts, and layouts for pitching ideas.",
  },
  {
    icon: <SiCodeforces />,
    label: "Codeforces",
    color: "text-orange-400",
    desc: "Competitive programming platform with rated contests — sharpens algorithms, data structures, and problem-solving.",
  },
  {
    icon: <SiCodechef />,
    label: "CodeChef",
    color: "text-amber-500",
    desc: "Global competitive programming community hosting long challenges and cook-offs to build contest experience.",
  },
  {
    icon: <SiLeetcode />,
    label: "LeetCode",
    color: "text-yellow-400",
    desc: "Premier platform for coding interview prep — covers arrays, graphs, DP, and system design used by top tech companies.",
  },
  {
    icon: <SiHackerrank />,
    label: "Hackerrank",
    color: "text-green-400",
    desc: "Platform for practicing coding skills and preparing for technical interviews — offers a wide range of problems and contests.",
  },
];
